### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by lucellent** [camenduru/ProPainter-colab#2]
Using Colab Pro with High RAM and V100 GPU

<img width="1651" alt="Screenshot_157" src="https://github.com/camenduru/ProPainter-colab/assets/38135928/e27b9c3e-06ce-47fa-a7c9-cb35fa90759c">

**Comment by camenduru** [comment]
This is for T4. Change this line with the one below:
```py
!pip install -q https://github.com/camenduru/wheels/releases/download/colab/mmcv_full-1.7.1-cp310-cp310-linux_x86_64.whl
```
It will take ~1 hour to build.
```py
%cd /content
!git clone -b v1.7.1 https://github.com/open-mmlab/mmcv
%cd /content/mmcv
!MMCV_WITH_OPS=1 pip install -v .
%cd /content/ProPainter
```

**Comment by lucellent** [comment]
> This is for T4. Change this line with the one below:
> 
> ```python
> !pip install -q https://github.com/camenduru/wheels/releases/download/colab/mmcv_full-1.7.1-cp310-cp310-linux_x86_64.whl
> ```
> 
> It will take ~1 hour to build.
> 
> ```python
> %cd /content
> !git clone -b v1.7.1 https://github.com/open-mmlab/mmcv
> %cd /content/mmcv
> !MMCV_WITH_OPS=1 pip install -v .
> %cd /content/ProPainter
> ```

The line looks the same like the one already in the Colab

I did try with T4 first but CUDA was out of memory, so I switched to V100
